## Préambule
site_name: mon_site
site_description: Un site sur quelque chose.
site_author: Michel Tibo

theme: 
  name: readthedocs # mkdocs

## Architecture
nav:
  - Accueil: index.md

## Extensions
